- name: Oracle installation and configuration
  hosts: oracle
  gather_facts: True
  vars_files:
    - roles/oracle/defaults/main.yml    
    - roles/linux/defaults/main.yml    
    - vars/vars.yml
  roles:
    - role: oracle 
  tags:
    - oracle_config
