---
- name: Install requirements for running the playbooks
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Install python libraries
      pip:
        name:
          - netapp-lib
          - xmltodict
	  - jmespath
