---
#Create Oracle base directory
- block:
   - name: Create Oracle base directory
     file:
       state: directory
       path: '{{ oracle_base }}'
       owner: '{{ oracle_user }}'
       group: '{{ oracle_install_group }}'
     become: true
     tags:
       - oracle_base

#Create Oracle data directory
   - name: Create Oracle data directory
     file:
       state: directory
       path: '{{ oracle_data }}'
       owner: '{{ oracle_user }}'
       group: '{{ oracle_install_group }}'
     become: true
     tags:
       - oracle_data

#Create Oracle recovery directory
   - name: Create Oracle recovery directory
     file:
       state: directory
       path:  '{{ oracle_reco }}'
       owner: '{{ oracle_user }}'
       group: '{{ oracle_install_group }}'
     become: true
     tags:
       - oracle_reco
