---
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# Create mount points for NFS file systems
# Mount NFS file systems on Oracle hosts
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------

- block:
    - name: Create mount points for NFS file systems / Mount NFS file systems on Oracle hosts
      include_tasks: mount_points.yml
      tags:
        - cre_mount_points
        - mount_host_datastores

# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# Install required packages, copy and install rpm
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
    - name: Install required packages
      include_tasks: preinstall_rpm.yml
      tags:
        - preinstall_rpm
        - cp_compat-libcap1-1.10
        - inst_compat-libcap1-1.10 

# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# Create Oracle base directory
# Create Oracle data directory
# Create Oracle recovery directory
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
    - name: Create Oracle base directories
      include_tasks: create_database.yml
      tags:
        - oracle_base
        - oracle_data
        - oracle_reco

# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# Disable transparent hugepages in current system
# Disable transparent hugepages at reboot
# Configure Kernel for hugepages
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
    - name: Disable transparent hugepages and configure kernel for hugepages
      include_tasks: huge_pages.yml
      tags:
        - disable_thp
        - config_hugepages

# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# Disable SELinux
# Disable Firewall Deamon
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
    - name: Disable firewall deamon/SELinux
      include_tasks: disable_se.yml
      tags:
        - disable_selinux
        - disable_firewall

# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# Enable chronyd service
# Start chronyd service
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
    - name: Enable chronyd and Start chronyd service
      include_tasks: enable_chronyd.yml
      tags:
        - enable_chronyd
        - start_chronyd

# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# Increase file descriptor hard limit
# Increase min stack size
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
    - name: Increase file descriptor hard limit
      include_tasks: descriptor_limit.yml

# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# Create pam.d Session File
# Enable limits change without reboot
# Create a pam.d Session non-interactive file
# Add a line to enable limits change without reboot
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
    - name:  Create Session Files
      include_tasks: session_files.yml
