- name: Configure oracle user env - add oracle_home variable
  lineinfile: 
    dest: "/home/{{ oracle_user }}/.bashrc" 
    line: "export ORACLE_HOME={{ oracle_home }}"
  become: true
  become_user: '{{ oracle_user }}'
  tags:
    - set_oracle_home

- name: Configure oracle user env - add oracle_sid variable 
  when: db_instance == "SI"
  lineinfile: 
    dest: "/home/{{ oracle_user }}/.bashrc" 
    line: "export ORACLE_SID={{ oracle_sid }}"
  become: true
  become_user: '{{ oracle_user }}'
  tags:
    - set_oracle_sid

- name: Configure oracle user env - add oracle exe to PATH
  lineinfile: 
    dest: "/home/{{ oracle_user }}/.bashrc" 
    line: "export PATH=$PATH:$ORACLE_HOME/bin"
  become: true
  become_user: '{{ oracle_user }}'
  tags:
    - set_oracle_path