# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# Create Oracle database instance from template using dbca utility
# Create number of PDBs within the instance container as specified by user
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
- block:
    - name: Generate response file for dbca for single instance Oracle setup
      template:
        src: "dbca.rsp.{{ ora_version }}"
        dest: "{{ installation_folder }}/dbca.rsp"
      become: true
      become_user: '{{ oracle_user }}'

    - name: Create database for single Oracle instance
      command: "{{ oracle_home }}/bin/dbca -silent -createDatabase -responseFile {{ installation_folder }}/dbca.rsp"
      become: true
      become_user: '{{ oracle_user }}'
  tags:
    - create_database
