---
- name: Create folder for Oracle installation files
  file:
    state: directory
    path: '{{ installation_folder }}'
    owner: '{{ oracle_user }}'
    group: '{{ oracle_install_group }}'
  become: true
  tags:
    - create_installation_dir

- name: Create folder for installer files
  file:
    state: directory
    path: '{{ installer_dir }}'
    owner: '{{ oracle_user }}'
    group: '{{ oracle_install_group }}'
  become: true
  tags:
    - create_installer_dir