# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# Create Oracle listener using netca configuration utility
# Create a custom listener identified by instance name and a specific port
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
- block:
    - name: Generate listener response file
      template:
        src: "netca.rsp.{{ ora_version }}"
        dest: "{{ installation_folder }}/netca.rsp"
      become: true
      become_user: '{{ oracle_user }}'

    - name: Create listener using netca
      command: "{{ oracle_home }}/bin/netca -silent -responseFile {{ installation_folder }}/netca.rsp"
      become: true
      become_user: '{{ oracle_user }}'
  tags:
    - create_listener
