# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# Create Oracle listener using netca configuration utility
# Create a custom listener identified by instance name and a specific port
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
- block:
    - name: Generate listener response file
      template:
        src: "netca.rsp.{{ ora_version }}"
        dest: "{{ installation_folder }}/netca.rsp"
      become: true
      become_user: '{{ oracle_user }}'

    - name: Create listener using netca
      command: "{{ oracle_home }}/bin/netca -silent -responseFile {{ installation_folder }}/netca.rsp"
      become: true
      become_user: '{{ oracle_user }}'
  rescue:
    - name: Failure message
      debug:
        msg:
          - "TASK [Create oracle listener] FAILED. Hints:"
          - 1. Check the error message.
          - 2. Check the netca.rsp file configuration on target hosts.
          - 3. Check whether the task file exists.
          - 4. Check whether the task file name and extension is correct.
  tags:
    - create_listener
