# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# Create Oracle listener using netca configuration utility
# Create a custom listener identified by instance name and a specific port
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
- block:
    - name: Generate a target netca.rsp file at template dest to work around 'invalid selinux context' issue
      file:
        path: "{{ installation_folder }}/netca.rsp"
        state: touch
      become: true
      become_user: '{{ oracle_user }}'
      tags:
        - gen_netca_rsp

    - name: Generate listener response file
      template:
        src: "netca.rsp.{{ ora_version }}"
        dest: "{{ installation_folder }}/netca.rsp"
      become: true
      become_user: '{{ oracle_user }}'
      tags:
        - gen_netca_rsp

    - name: Create listener using netca
      command: "{{ oracle_home }}/bin/netca -silent -responseFile {{ installation_folder }}/netca.rsp"
      become: true
      become_user: '{{ oracle_user }}'
  tags:
    - create_listener
