# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# Create Oracle database instance from template using dbca utility
# Create number of PDBs within the instance container as specified by user
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
- block:
    - name: Generate a target dbca.rsp file at template dest to work around 'invalid selinux context' issue
      file:
        path: "{{ installation_folder }}/dbca.rsp"
        state: touch
      become: true
      become_user: '{{ oracle_user }}'
      tags:
        - gen_dbca_rsp

    - name: Generate response file for dbca for single instance Oracle setup
      template:
        src: "dbca.rsp.{{ ora_version }}"
        dest: "{{ installation_folder }}/dbca.rsp"
      become: true
      become_user: '{{ oracle_user }}'
      tags:
        - gen_dbca_rsp

    - name: Create database for single Oracle instance
      command: "{{ oracle_home }}/bin/dbca -silent -createDatabase -responseFile {{ installation_folder }}/dbca.rsp"
      become: true
      become_user: '{{ oracle_user }}'
  tags:
    - create_database
