- name: Disable default listener startup from dbstart script
  ansible.builtin.replace:
    path: "{{ oracle_home }}/bin/dbstart"
#    regexp: '^$ORACLE_HOME/bin/lsnrctl start >> $LOG'
    regexp: '^(?=.*?\bORACLE_HOME\b)(?=.*?\bstart\b)(?=.*?\bLOG\b).*$'
    replace: '#    $ORACLE_HOME/bin/lsnrctl start >> $LOG 2>&1 &'
  become: true
  become_user: '{{ oracle_user }}'
  tags:
    - turnoff_default_listener