# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# Oracle direct NFS bypass OS buffer cache to access NFS file system to improve performance.
# Oracle dNFS is not enabled by default. The tasks setup the dNFS client and configure dNFS setting.
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
- block:
    - name: Enable oracle dNFS - create odm dir
      file:
        state: directory
        path: "{{ oracle_home }}/rdbms/lib/odm"
        owner: '{{ oracle_user }}'
        group: '{{ oracle_install_group }}'
        mode: 0755
      become: true

    - name: Enable oracle dnfs - Copy nfsodm lib file to odm directory
      ansible.builtin.copy:
        src: "{{ oracle_home }}/lib/libnfsodm19.so"
        dest: "{{ oracle_home }}/rdbms/lib/odm"
        remote_src: true
      become: true
      become_user: '{{ oracle_user }}'
  rescue:
    - name: Failure message
      debug:
        msg:
          - "TASK [Enable dnfs client] FAILED. Hints:"
          - 1. Check the failure error message.
          - 2. Check whether the task file exists.
          - 3. Check whether the task file name and extension is correct.
  tags:
    - enable_dnfs_client
