- name: Generate a target netca.rsp file at template dest to work around 'invalid selinux context' issue
  file:
    path: "{{ installation_folder }}/netca.rsp"
    state: touch
  become: true
  become_user: '{{ oracle_user }}'
  tags:
    - gen_netca_rsp

- name: Generate listener response file
  template:
    src: "netca.rsp.{{ ora_version }}"
    dest: "{{ installation_folder }}/netca.rsp"
  become: true
  become_user: '{{ oracle_user }}'
  tags:
    - gen_netca_rsp
