- name: Generate a target file at template dest to work around 'invalid selinux context' issue
  file:
    path: "{{ installation_folder }}/db_install.rsp"
    state: touch
  become: true
  become_user: '{{ oracle_user }}'
  tags:
    - gen_db_install_rsp

- name: Generate the response file for software only installation
  ansible.builtin.template:
    src: "db_install.rsp.{{ ora_version }}"
    dest: "{{ installation_folder }}/db_install.rsp"
  become: true
  become_user: '{{ oracle_user }}'
  tags:
    - gen_db_install_rsp
