---
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# Create folder for Oracle installation files
# Create folder for installer files
# Copy Oracle 19c install file to installer directory
# Copy DB RU 19.8 file to installer directory
# Copy latest OPatch file to installer directory
# Unpack Oracle 19c installer files
# Delete existing OPatch directory in oracle home
# Extract current version of OPatch files - p6880880
# Unpack DB 19.8 RU patch files
# Generate a target file at template dest to work around 'invalid selinux context' issue
# Generate the response file for software only installation
# Set ASSUME_DISTID to OL7
# Install oracle software 19c
# Execute Inventory root command
# Execute DB home root command
# Generate a target netca.rsp file at template dest to work around 'invalid selinux context' issue
# Generate listener response file
# Create listener using netca
# Generate a target dbca.rsp file at template dest to work around 'invalid selinux context' issue
# Generate response file for dbca for single instance Oracle setup
# Create database for single Oracle instance
# Configure oracle user env - add oracle_home variable
# Configure oracle user env - add oracle_sid variable
# Configure oracle user env - add oracle exe to PATH
# Generate a target oranfstab file at template dest to work around 'invalid selinux context' issue
# Generate oranfstab file to setup dnfs volume access
# Enable oracle dNFS client
# Copy pdb save state script to oracle host
# Maintain pdbs open state after a instance restart
# Copy archivelog script to oracle host
# Enable database to archive log if log_archive_mode is true
# Update oratab to start oracle_sid
# Create DB start/shutdown script for each instance sid
# Create symbolic link to rc0.d to shut down DB
# Create symbolic link to rcX.d to startup DB at runlevel 3 and 5
# Disable default listener startup from dbstart script
# Reboot Oracle server host
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
