---
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# DB software only installation tasks block
# Execute 19.3 base install and applied 19.8 patch in single installation
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
- block:
    - name: Oracle software only install
      include_tasks: oracle_install.yml
      tags:
        - software_only_install

# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# Create Oracle listener using netca configuration utility
# Create a custome listener identified by instance name and a specific port
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
    - name: Create Oracle listener
      include_tasks: create_listener.yml
      tags:
        - create_listener

# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# Create Oracle database instance from template using dbca utility
# Create number of PDBs within the instance container as specified by user
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
    - name: Create Oracle database
      include_tasks: create_database.yml
      tags:
        - create_database

# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# Configure oracle user environment to set SID, ORACLE_HOME, PATH
# For multiple databases on the same host, environment variables needs to be switched by user for access intended DB
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
    - name: Oracle env config
      include_tasks: oracle_env_config.yml
      tags:
        - ora_env_config

# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# PDBs within a DB instance will not automatically start after a bounce 
# Save PDBs active state will allow PDBs return to its active state after a bounce
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
    - name: Save PDB state
      include_tasks: save_pdb_state.yml
      tags:
        - ora_save_pdb_state

# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# Default Oracle instanace is in noarchive mode after initial creation.
# Archive mode enables online backup of Oracle DBs.
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
    - name: Enable instance archive mode
      include_tasks: enable_archive_mode.yml
      tags:
        - enable_archive_mode

# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# Oracle direct NFS bypass OS buffer cache to access NFS file system to improve performance. 
# Oracle dNFS is not enabled by default. The tasks setup the dNFS client and configure dNFS setting.
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
    - name: Enable dnfs client 
      include_tasks: enable_dnfs_client.yml
      tags:
        - enable_dnfs_client

# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# Configure to automatically shutdown Oracle database instances and listeners when OS is rebooted.
# Configure to automatically startup Oracle database instances and listeners when OS is rebooted.
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
    - name: Enable DB auto startup and shutdown between OS reboot
      include_tasks: enable_db_start_shut.yml
      tags:
        - enable_db_start_shut
        - ora_update_oratab
