# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# Configure oracle user environment to set SID, ORACLE_HOME, PATH
# For multiple databases on the same host, environment variables needs to be switched by user for access intended DB
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
- block:
    - name: Configure oracle user env - add oracle_sid variable
      when: db_instance == "SI"
      lineinfile:
        dest: "/home/{{ oracle_user }}/.bash_profile"
        line: "export ORACLE_SID={{ oracle_sid }}"
      become: true
      become_user: '{{ oracle_user }}'

    - name: Configure oracle user env - add oracle_home and path variable
      lineinfile:
        dest: "/home/{{ oracle_user }}/.bash_profile"
        line: "export ORACLE_HOME={{ oracle_home }};PATH=$PATH:$ORACLE_HOME/bin"
      become: true
      become_user: '{{ oracle_user }}'
  tags:
    - ora_env_config
