- name: Generate a target oranfstab file at template dest to work around 'invalid selinux context' issue
  file:
    path: "{{ oracle_home }}/dbs/oranfstab"
    state: touch
  become: true
  become_user: '{{ oracle_user }}'
  tags:
    - gen_oranfstab

- name: Generate oranfstab file to setup dnfs volume access
  template:
    src: "dnfs.{{ ora_version }}"
    dest: "{{ oracle_home }}/dbs/oranfstab"
  become: true
  become_user: '{{ oracle_user }}'
  tags:
    - gen_oranfstab
