- name: Create symbolic link to rc0.d to shut down DB
  ansible.builtin.file:
    src: "/etc/init.d/dbora.{{ oracle_sid }}"
    dest: "/etc/rc.d/rc0.d/K01dbora.{{ oracle_sid }}"
    state: link
  become: true
  tags:
    - lnk_dbora_shut

- name: Create symbolic link to rcX.d to startup DB at runlevel 3 and 5
  ansible.builtin.file:
    src: "/etc/init.d/dbora.{{ oracle_sid }}"
    dest: "/etc/rc.d/rc{{ item }}.d/S99dbora.{{ oracle_sid }}"
    state: link
  become: true
  loop:
    - 3
    - 5
  tags:
    - lnk_dbora_start