---
- name: Create database for single Oracle instance
  when: db_instance == "SI"
  command: "{{ oracle_home }}/bin/dbca -silent -createDatabase -responseFile {{ installation_folder }}/dbca.rsp"
  become: true
  become_user: '{{ oracle_user }}'
  tags:
    - exec_dbca_si
