- name: Unpack Oracle 19c installer files
  ansible.builtin.unarchive:
    src: "{{ installer_dir }}/{{ installer_archives[0] }}"
    dest: "{{ installation_folder }}/"
    remote_src: yes
  become: true
  become_user: '{{ oracle_user }}'
  tags:
    - unzip_install_archives

- name: Delete existing OPatch directory in oracle home
  ansible.builtin.file:
    path: "{{ oracle_home }}/OPatch"
    state: absent
  become: true
  become_user: '{{ oracle_user }}'
  tags:
    - del_exist_opatch_ohome

- name: Extract current version of OPatch files - p6880880
  ansible.builtin.unarchive:
    src: "{{ installer_dir }}/{{ installer_archives[2] }}"
    dest: "{{ oracle_home }}/"
    remote_src: yes
  become: true
  become_user: '{{ oracle_user }}'
  tags:
    - unzip_opatch_file_oracle

- name: Unpack DB 19.8 RU patch files
  ansible.builtin.unarchive:
    src: "{{ installer_dir }}/{{ installer_archives[1] }}"
    dest: "{{ installer_dir }}/"
    remote_src: yes
  become: true
  become_user: '{{ oracle_user }}'
  tags:
    - unzip_oracle_ru_file
